// 内置句库：成人日常口语，6 个场景 × 10 句。
// tip 用于提示连读、失爆、重音等发音要点。

export const BUILTIN_COURSES = [
  {
    id: 'greetings',
    title: '问候寒暄',
    emoji: '👋',
    sentences: [
      { id: 'greetings-1', en: "How's it going?", zh: '最近怎么样？', tip: "How's it 连读成 /haʊzɪt/" },
      { id: 'greetings-2', en: 'Long time no see.', zh: '好久不见。', tip: '三个词都重读，语气轻快' },
      { id: 'greetings-3', en: 'Nice to meet you.', zh: '很高兴认识你。', tip: 'meet you 连读成 /miːtʃu/' },
      { id: 'greetings-4', en: "I've heard a lot about you.", zh: '久仰大名。', tip: 'heard a 连读，a 弱读' },
      { id: 'greetings-5', en: 'What have you been up to?', zh: '你最近在忙什么？', tip: 'been up to 连读成 /bɪnʌptə/' },
      { id: 'greetings-6', en: "I'm doing pretty well, thanks.", zh: '我挺好的，谢谢。', tip: 'pretty 的 t 轻读接近 d' },
      { id: 'greetings-7', en: 'Say hi to your family for me.', zh: '替我向你家人问好。', tip: 'hi to 的 t 失爆不发音' },
      { id: 'greetings-8', en: 'It was really nice talking to you.', zh: '跟你聊天很开心。', tip: 'talking to 的 g 不发音' },
      { id: 'greetings-9', en: "Let's catch up sometime soon.", zh: '我们找时间聊聊。', tip: 'catch up 连读成 /kætʃʌp/' },
      { id: 'greetings-10', en: 'Take care and see you around.', zh: '多保重，回头见。', tip: 'see you 连读成 /siːju/' },
    ],
  },
  {
    id: 'ordering',
    title: '点餐',
    emoji: '🍽️',
    sentences: [
      { id: 'ordering-1', en: 'Could I see the menu, please?', zh: '可以给我看一下菜单吗？', tip: 'Could I 连读成 /kʊdaɪ/' },
      { id: 'ordering-2', en: "I'd like a cup of coffee, please.", zh: '我想要一杯咖啡。', tip: 'cup of 连读成 /kʌpəv/' },
      { id: 'ordering-3', en: 'What do you recommend?', zh: '你有什么推荐吗？', tip: 'What do you 弱读成 /wɒdəjə/' },
      { id: 'ordering-4', en: 'Can I get this without onions?', zh: '这个可以不加洋葱吗？', tip: 'get this 的 t 失爆' },
      { id: 'ordering-5', en: "I'll have the same, please.", zh: '我也要一样的。', tip: "I'll have 连读成 /aɪləv/" },
      { id: 'ordering-6', en: 'Is this dish spicy?', zh: '这道菜辣吗？', tip: 'dish 结尾的 sh 要轻而短' },
      { id: 'ordering-7', en: 'Could we get the check, please?', zh: '可以买单吗？', tip: 'check 的 k 轻送气' },
      { id: 'ordering-8', en: 'Do you have any vegetarian options?', zh: '有素食选择吗？', tip: 'vegetarian 重音在第三个音节' },
      { id: 'ordering-9', en: "It's delicious, thank you.", zh: '很好吃，谢谢。', tip: 'delicious 重音在第二个音节' },
      { id: 'ordering-10', en: "I'm allergic to peanuts.", zh: '我对花生过敏。', tip: 'allergic to 连读，重音在 -ler-' },
    ],
  },
  {
    id: 'directions',
    title: '问路',
    emoji: '🧭',
    sentences: [
      { id: 'directions-1', en: 'Excuse me, how do I get to the station?', zh: '打扰一下，去车站怎么走？', tip: 'Excuse me 连读成 /ɪkˈskjuːzmi/' },
      { id: 'directions-2', en: 'Is it far from here?', zh: '离这儿远吗？', tip: 'far from 连读成 /fɑːfrəm/' },
      { id: 'directions-3', en: 'Go straight and turn left.', zh: '直走然后左转。', tip: 'straight 的 t 失爆' },
      { id: 'directions-4', en: "It's about a ten-minute walk.", zh: '走路大概十分钟。', tip: 'about a 连读成 /əˈbaʊtə/' },
      { id: 'directions-5', en: 'Which bus goes downtown?', zh: '哪路公交去市中心？', tip: 'goes downtown 连读' },
      { id: 'directions-6', en: 'Could you show me on the map?', zh: '能在地图上指给我看吗？', tip: 'show me 连读成 /ʃəʊmi/' },
      { id: 'directions-7', en: "I think I'm lost.", zh: '我想我迷路了。', tip: "I'm lost 的 t 失爆" },
      { id: 'directions-8', en: "You can't miss it.", zh: '你不会找不到的。', tip: "can't miss 两个 t 都失爆" },
      { id: 'directions-9', en: "It's right across from the bank.", zh: '就在银行正对面。', tip: 'across from 连读' },
      { id: 'directions-10', en: "Thanks, you've been a big help.", zh: '谢谢，你帮了大忙。', tip: 'been a 连读成 /bɪnə/' },
    ],
  },
  {
    id: 'shopping',
    title: '购物',
    emoji: '🛍️',
    sentences: [
      { id: 'shopping-1', en: 'How much does this cost?', zh: '这个多少钱？', tip: 'much does 连读成 /mʌtʃdəz/' },
      { id: 'shopping-2', en: 'Do you have this in a smaller size?', zh: '这个有小一号的吗？', tip: 'in a 连读成 /ɪnə/' },
      { id: 'shopping-3', en: 'Can I try it on?', zh: '我可以试穿吗？', tip: 'try it on 连读成 /traɪɪtɒn/' },
      { id: 'shopping-4', en: "It's a bit too expensive for me.", zh: '对我来说有点贵。', tip: 'bit too 的 t 失爆' },
      { id: 'shopping-5', en: 'Is there any discount?', zh: '有折扣吗？', tip: 'there any 连读成 /ðeərəni/' },
      { id: 'shopping-6', en: "I'll take it.", zh: '我买了。', tip: 'take it 连读成 /teɪkɪt/' },
      { id: 'shopping-7', en: 'Can I pay by card?', zh: '可以刷卡吗？', tip: 'pay by 连读' },
      { id: 'shopping-8', en: 'Could I get a receipt?', zh: '可以给我一张收据吗？', tip: 'get a 连读，receipt 的 p 不发音' },
      { id: 'shopping-9', en: "I'm just looking, thanks.", zh: '我只是看看，谢谢。', tip: 'just looking 的 t 失爆' },
      { id: 'shopping-10', en: 'Do you offer a refund?', zh: '你们可以退款吗？', tip: 'offer a 连读成 /ˈɒfərə/' },
    ],
  },
  {
    id: 'phone',
    title: '打电话',
    emoji: '📞',
    sentences: [
      { id: 'phone-1', en: 'Hello, this is Li Ming speaking.', zh: '你好，我是李明。', tip: 'this is 连读成 /ðɪsɪz/' },
      { id: 'phone-2', en: 'Can I speak to Anna, please?', zh: '我可以和安娜通话吗？', tip: 'speak to 连读成 /spiːktə/' },
      { id: 'phone-3', en: 'Could you hold on a moment?', zh: '请稍等一下。', tip: 'hold on 连读成 /həʊldɒn/' },
      { id: 'phone-4', en: "Sorry, you've got the wrong number.", zh: '抱歉，你打错了。', tip: 'got the 的 t 失爆' },
      { id: 'phone-5', en: 'Can I leave a message?', zh: '我可以留言吗？', tip: 'leave a 连读成 /liːvə/' },
      { id: 'phone-6', en: "I'll call you back later.", zh: '我晚点打给你。', tip: 'call you 连读成 /kɔːlju/' },
      { id: 'phone-7', en: 'The line is busy right now.', zh: '现在占线。', tip: 'busy 的 s 发 /z/' },
      { id: 'phone-8', en: 'Could you speak a little slower?', zh: '你能说慢一点吗？', tip: 'a little 连读，两个 t 轻读成 d' },
      { id: 'phone-9', en: "Sorry, I can't hear you clearly.", zh: '抱歉，我听不清。', tip: "can't hear 的 t 失爆" },
      { id: 'phone-10', en: 'Thanks for calling.', zh: '谢谢来电。', tip: 'for 弱读成 /fə/' },
    ],
  },
  {
    id: 'work',
    title: '工作寒暄',
    emoji: '💼',
    sentences: [
      { id: 'work-1', en: 'How was your weekend?', zh: '周末过得怎么样？', tip: 'was your 连读成 /wəzjə/' },
      { id: 'work-2', en: "I've been really busy lately.", zh: '我最近特别忙。', tip: 'been really 连读' },
      { id: 'work-3', en: 'Did you see the email I sent?', zh: '你看到我发的邮件了吗？', tip: 'sent 的 t 失爆' },
      { id: 'work-4', en: "Let's grab lunch together.", zh: '我们一起吃午饭吧。', tip: 'grab lunch 的 b 失爆' },
      { id: 'work-5', en: 'Can we schedule a quick meeting?', zh: '我们能约个短会吗？', tip: 'schedule 美式 /ˈskedʒuːl/' },
      { id: 'work-6', en: "I'm working on it right now.", zh: '我正在处理。', tip: 'on it 连读成 /ɒnɪt/' },
      { id: 'work-7', en: 'Could you send me the file?', zh: '能把文件发给我吗？', tip: 'send me 的 d 失爆' },
      { id: 'work-8', en: 'That sounds like a good idea.', zh: '听起来是个好主意。', tip: 'sounds like 连读' },
      { id: 'work-9', en: "I'll get back to you by Friday.", zh: '我周五前回复你。', tip: 'get back 的 t 失爆' },
      { id: 'work-10', en: 'Great job on the presentation.', zh: '演示做得很好。', tip: 'job on 连读成 /dʒɒbɒn/' },
    ],
  },
];

// 用户自建句子的归属场景（内置场景之外的一个额外分类）。
export const MY_COURSE = { id: 'mine', title: '我的句子', emoji: '✏️' };
